[package]
name = "ucpack"
version = "0.1.0"
edition = "2021"

[features]
default = ["strict", "std"]
std = []
strict = []

[[test]]
name = "std"
required-features = ["std"]

[dependencies]
serde = { version = "1.0.214", default-features = false, features = ["derive"] }
